### ISSUE TITLE
Make QPong Online

### ISSUE THREAD

**Issue by tula3and** [qiskit-community/qiskit-hackathon-korea-22#14]
# Abstract
QPong is a ping pong game using quantum gates made by Huang Junye. Let's try to make QPong online and play with Qiskit community!

# Description 
If you are interested in using Python and making a online game, this project is for you! 🎮
- QPong repository: [https://github.com/HuangJunye/QPong](https://github.com/HuangJunye/QPong)
- QPong Unity repository: [https://github.com/HuangJunye/QPong-Unity](https://github.com/HuangJunye/QPong-Unity)

# Members
 - @tula3and
 - Slack: `@Dayeong Kang`
 - Qiskit Coach: @tula3and

# Deliverable

# GitHub repo

**Comment by OHINHYUK55** [comment]
I am interested in this project. Can I join this project?

**Comment by tula3and** [comment]
@OHINHYUK55 Sure. Thanks for joining! 👍

**Comment by starktech23** [comment]
@tula3and @0sophy1 I'll be supporting this project as well :)

**Comment by tula3and** [comment]
@starktech23 Welcome! Thank you for joining as a mentor :)

**Comment by 0sophy1** [comment]
4시에 네트워크 존에 오셔서 프로젝트 설명하고 멤버 모아보세요!

**Comment by OHINHYUK55** [comment]
@tula3and 죄송한데 다른 프로젝트 해보고싶은게 생겨서 바꿔도 될까요?

**Comment by tula3and** [comment]
@OHINHYUK55 넵 알겠습니다~

**Comment by 0sophy1** [comment]
다음기회에!
