### ISSUE TITLE
Visual Studio Code extension for Qiskit

### ISSUE THREAD

**Issue by ucyang** [qiskit-community/qiskit-hackathon-korea-22#16]
# Abstract

Fork and develop [the Visual Studio Code extension for Qiskit development](https://github.com/qiskit-community/qiskit-vscode).

# Description 

The extension's repository has been archived and is not being actively developed.
Also, it is not published through the [Open VSX Registry](https://open-vsx.org/), which is the marketplace of extensions for VS Code compatible editors, e.g., [VSCodium](https://vscodium.com/).

Let's fork and enhance the extension.

# Members

 
 
 - TBD
 - Qiskit Coach: TBD 

# Deliverable

TBA

# GitHub repo

TBA

**Comment by tula3and** [comment]
I am interested in this project!

**Comment by 0sophy1** [comment]
4시에 네트워크 존에 오셔서 프로젝트 설명하고 멤버 모아보세요!

**Comment by dongsin-kim** [comment]
I love the idea-!

**Comment by 0sophy1** [comment]
See you next time!
