### ISSUE TITLE
 Bloch multivector visualization enhancement for qiskit-terra 

### ISSUE THREAD

**Issue by mrvee-qC** [qiskit-community/qiskit-hackathon-korea-22#28]
# Abstract

Modifying/adding functionality to plot_bloch_multivector, to be able to plot multiple statevectors on the same Bloch sphere for easy visualization of change in state [https://github.com/Qiskit/qiskit-terra/issues/5021](https://github.com/Qiskit/qiskit-terra/issues/5021)

# Description 
It would be a great learning and visualization tool if something like this could be added! Here is a visualization of what can be expected! The relevant functions lie here: [https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/visualization/state_visualization.py](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/visualization/state_visualization.py)

**Expected Behavior:**
#### Screenshot 1 - Red initial state -> Green final state
![bloch_multi](https://user-images.githubusercontent.com/61380731/146345914-e6026769-ac2e-4afb-999d-355c3e6b3d23.png)

#### Screenshot 2 - State evolution ->
Colour coding maybe required to be specified for standardization but it can be great to show visualisations of how state evolves!

![bloch_multi_with_angle](https://user-images.githubusercontent.com/61380731/146346060-a93969bc-ca75-4bde-9e0a-fada7c442f15.png)

Example implementation used as a learning tool - https://gitlab.com/qworld/silve
# Members

 - @githubhandle - (Add team github names here in the format below)
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @mrvee-qC | Slack: @Vishal B. | E-Mail: vishal.bajpe@gmail.com

# Deliverable

A PR in the Qiskit Terra repo or a demonstration of a work towards PR for the qiskit terra repo to be included as a new feature request.

# GitHub repo

TBA

**Comment by Eungi20** [comment]
I want to join this project!

**Comment by obliviateandsurrender** [comment]
@mrvee-qC An interesting tool to look at for this project might also be the [Kaleidoscope Project](https://nonhermitian.org/kaleido/install.html), as it supports the multivector visualization using Qiskit.

**Comment by byuljwa** [comment]
I want to join this project

**Comment by Eungi20** [comment]
> I want to join this project!

Can I go to other project?

**Comment by mrvee-qC** [comment]
Hi @Eungi20 and @byuljwa!  You may search for other potential team mates to complete the group for this project! :) Seeing that the project hasn't reached its minimum limit, you can also look for other teams or feel free to contact Sophy if you need help finding teams/members!

**Comment by 0sophy1** [comment]
cheer Vishal!
